### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by xgrons** [N0x1s/egy_best#2]
ERROR:    Exception in ASGI application

https://pastr.de/v/3564152/raw

Any Help

**Comment by N0x1s** [comment]
Thanks for reaching out

The problem is from the CSS selector that was used to bypass the antibot (.bigbutton._reload)
The website devs are constantly changing the layout, CSS values
using a headless browser to get the content is not a valid solution  

**Solutions**
- keeping track of every CSS selector and updating it frequently
- reverse the obfuscated javascript function that is responsible for generating the auth token


This code was written a while ago and need some serious refactoring
I'm might be able to do so but I'm not promising anything in the near future

**Comment by xgrons** [comment]
Thank you for your response 
at first i thought because egybest only allow arabic ip so problem might be proxy
i will be waiting for update :)
